if(MSVC)
  return()
endif()
set(POPPLER_PACKAGE_VERSION 0.24)
set(POPPLER_REPO_URL https://github.com/BlueBrain/Poppler.git)
set(POPPLER_REPO_TAG bbp)
set(POPPLER_OPTIONAL ON)
set(POPPLER_CMAKE_ARGS -DENABLE_UTILS=OFF -DENABLE_GLIB=OFF
    -DCOMPILE_WARNINGS=no -DDEFAULT_COMPILE_WARNINGS_NO=-w
)
set(POPPLER_DEPENDS REQUIRED Qt4)
set(POPPLER_CMAKE_INCLUDE "SYSTEM")

